-- +goose Up
CREATE TABLE goods_ref(
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    name TEXT NOT NULL,
    price INTEGER NOT NULL CHECK(price >= 0),
    volume REAL NOT NULL CHECK(volume > 0),
    ppv REAL GENERATED ALWAYS AS (price / volume),
    illegal TEXT DEFAULT 'no',
    dangerous TEXT DEFAULT 'no'
);
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Processor',0.1,7858,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Body Armor',1.5,95906,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Acron Drug',0.1,6000,'yes','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Morn Drug',0.1,5000,'yes','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Targeting System',0.75,29674,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Computation Mainframe',1,37940,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Anti-Grav Generator',2.5,71632,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Targeting Card',0.5,11873,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Mining Robot',8,145977,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fusion Generator',2.5,39553,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Slave',1,15000,'yes','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Diamond',0.05,750,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Electromagnetic Charge',1,13985,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Force Generator',4,49576,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('War Robot',8,92186,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Electron Accelerator',12,125431,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Antigrav Unit',2.5,25391,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Microchip',0.1,896,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Neutron Accelerator',15,125431,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Proton Accelerator',15,125431,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Gem',0.05,400,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Energy Generator',2,15957,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Display',1,7858,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Jewelry',0.2,1260,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Laser Modulator',3,16742,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Servo',0.25,1387,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('High Capacity Lens',1,4689,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Laser Compressor',1.5,6577,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Satellite',15,65714,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Gauss Rail',2,7735,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Teleporter',12,39365,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Vehicle',25,77087,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Medical Supplies',1,3006,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Rocket',4,11250,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Nanobot',0.5,1338,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Luxury Food',2.5,6452,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Gun',0.5,1232,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Laser Head',2,4690,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Military Tesla Coil',4.5,10314,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Turbine',7.5,16729,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fusion Core',2.5,5114,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Energy Tube',1.5,2895,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Warhead',3,5630,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Industrial Tesla Coil',5.5,10314,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Adhesive',0.25,402,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Book',0.2,319,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Platinum',0.5,750,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Liquor',1.25,1867,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Semi Conductor',0.1,129,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Ammunition',3,3786,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fuel',1,1232,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Gold',0.5,600,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Solar Panel',6,6858,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Conductor',0.15,168,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Transformator',0.2,209,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Drill',20,20443,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Explosive Charge',1.5,1423,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Coffee',0.2,187,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Spices',0.3,268,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Ammunition S',0.5,422,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('High Pressure Tube',2,1650,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Coolant',0.5,402,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Drone',10,7754,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Plasma Cell',0.25,174,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Rubber',1,686,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Electro Magnet',0.75,483,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Food',0.5,300,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Silver',0.5,300,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Tools',0.4,214,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Silicium',1,500,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Oil',1,490,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Paint',1,481,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Food Bar',0.5,223,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Cocoa',0.2,87,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Beer',0.5,216,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Energy Inverter',3,1277,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Carbon',1,423,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Acid',1,402,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Chemicals',1,402,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Solvent',1,402,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Wine',0.5,182,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Copper',1,350,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Protein',0.1,34,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Mineral',1.5,500,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fertilizer',1,319,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fish',0.5,152,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Ammunition M',1.5,422,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Steel',1,277,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Plastic',0.5,137,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Metal Plate',3,792,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fluorine',1,250,'no','yes');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Zinc',1,250,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Power Unit',5,1211,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Energy Container',4.5,1087,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Steel Tube',3,704,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Solar Cell',2,469,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Bio Gas',1,213,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Aluminium',1,200,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Lead',1,200,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Neon',1,200,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Wire',0.5,95,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Tea',0.2,37,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Glass',1,182,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Cattle',1.5,254,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Ammunition L',2.5,422,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Chlorine',1,150,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Hydrogen',1,150,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Raw Oil',1,150,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Wood',2.5,350,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Sheep',1,130,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Crystal',1.5,190,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fruit',0.5,56,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Clothes',1,102,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Coal',2,200,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Energy Cell',0.5,50,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fabric',1,91,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Oxygen',1,80,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Leather',0.5,37,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Meat',0.5,37,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Helium',1,50,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Plankton',1,50,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Fungus',1,46,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Paper',1,46,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Nitrogen',1,40,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Ore',2,70,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Vegetable',1,32,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Corn',1,28,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Potato',1,24,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Wheat',1,23,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Water',1,20,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Dairy',1,19,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Rice',1,15,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Plant',1.5,14,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Scrap Metal',3,25,'no','no');
INSERT INTO goods_ref(name,volume,price,illegal,dangerous) VALUES('Toxic Waste',4,15,'no','yes');

-- +goose Down
DROP TABLE goods_ref;
